CREATE DATABASE IF NOT EXISTS ai_study_note DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ai_study_note;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS sys_user_role;
DROP TABLE IF EXISTS sys_role;
DROP TABLE IF EXISTS ai_usage_log;
DROP TABLE IF EXISTS ai_config;
DROP TABLE IF EXISTS ai_chat_record;
DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS login_log;
DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS favorite;
DROP TABLE IF EXISTS note_tag;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS note;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS announcement;
DROP TABLE IF EXISTS sys_user;

CREATE TABLE sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '用户ID',
  username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
  password VARCHAR(100) NOT NULL COMMENT 'BCrypt加密密码',
  nickname VARCHAR(50) NOT NULL COMMENT '昵称',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  avatar VARCHAR(255) DEFAULT NULL COMMENT '头像URL',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1启用，0禁用',
  role VARCHAR(20) NOT NULL DEFAULT 'USER' COMMENT '角色：USER/ADMIN',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0否，1是'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

CREATE TABLE sys_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '角色ID',
  role_code VARCHAR(30) NOT NULL UNIQUE COMMENT '角色编码',
  role_name VARCHAR(50) NOT NULL COMMENT '角色名称',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统角色表';

CREATE TABLE sys_user_role (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  role_id BIGINT NOT NULL COMMENT '角色ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  UNIQUE KEY uk_user_role (user_id, role_id),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
  CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES sys_role(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';

CREATE TABLE category (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '分类ID',
  name VARCHAR(50) NOT NULL UNIQUE COMMENT '分类名称',
  description VARCHAR(255) DEFAULT NULL COMMENT '分类说明',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记分类表';

CREATE TABLE tag (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '标签ID',
  name VARCHAR(50) NOT NULL UNIQUE COMMENT '标签名称',
  color VARCHAR(20) DEFAULT '#409EFF' COMMENT '标签颜色',
  use_count INT NOT NULL DEFAULT 0 COMMENT '使用次数',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习标签表';

CREATE TABLE note (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '笔记ID',
  user_id BIGINT NOT NULL COMMENT '作者用户ID',
  category_id BIGINT DEFAULT NULL COMMENT '分类ID',
  title VARCHAR(150) NOT NULL COMMENT '笔记标题',
  content MEDIUMTEXT NOT NULL COMMENT 'Markdown正文',
  summary TEXT DEFAULT NULL COMMENT 'AI摘要',
  ai_key_points TEXT DEFAULT NULL COMMENT 'AI学习重点',
  ai_exam_points TEXT DEFAULT NULL COMMENT 'AI考试重点',
  ai_suggestion TEXT DEFAULT NULL COMMENT 'AI学习建议',
  status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/WAITING_AI/AI_FINISHED/PUBLISHED/ARCHIVED/DELETED',
  view_count INT NOT NULL DEFAULT 0 COMMENT '浏览数',
  like_count INT NOT NULL DEFAULT 0 COMMENT '点赞数',
  favorite_count INT NOT NULL DEFAULT 0 COMMENT '收藏数',
  comment_count INT NOT NULL DEFAULT 0 COMMENT '评论数',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  KEY idx_note_user (user_id),
  KEY idx_note_category (category_id),
  KEY idx_note_status (status),
  CONSTRAINT fk_note_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
  CONSTRAINT fk_note_category FOREIGN KEY (category_id) REFERENCES category(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='学习笔记表';

CREATE TABLE note_tag (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  note_id BIGINT NOT NULL COMMENT '笔记ID',
  tag_id BIGINT NOT NULL COMMENT '标签ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  UNIQUE KEY uk_note_tag (note_id, tag_id),
  CONSTRAINT fk_nt_note FOREIGN KEY (note_id) REFERENCES note(id),
  CONSTRAINT fk_nt_tag FOREIGN KEY (tag_id) REFERENCES tag(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记标签关联表';

CREATE TABLE favorite (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '收藏ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  note_id BIGINT NOT NULL COMMENT '笔记ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  UNIQUE KEY uk_favorite (user_id, note_id),
  CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES sys_user(id),
  CONSTRAINT fk_fav_note FOREIGN KEY (note_id) REFERENCES note(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记收藏表';

CREATE TABLE comment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '评论ID',
  note_id BIGINT NOT NULL COMMENT '笔记ID',
  user_id BIGINT NOT NULL COMMENT '评论用户ID',
  parent_id BIGINT DEFAULT NULL COMMENT '父评论ID',
  content VARCHAR(1000) NOT NULL COMMENT '评论内容',
  audit_status TINYINT NOT NULL DEFAULT 1 COMMENT '审核状态：0待审，1通过，2拒绝',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  KEY idx_comment_note (note_id),
  CONSTRAINT fk_comment_note FOREIGN KEY (note_id) REFERENCES note(id),
  CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='笔记评论表';

CREATE TABLE announcement (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '公告ID',
  title VARCHAR(120) NOT NULL COMMENT '公告标题',
  content TEXT NOT NULL COMMENT '公告内容',
  status TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1发布，0草稿',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统公告表';

CREATE TABLE ai_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'AI配置ID',
  provider VARCHAR(50) NOT NULL DEFAULT 'DeepSeek' COMMENT '供应商名称，如DeepSeek/OpenAI/阿里云百炼/智谱AI/本地模型',
  mode VARCHAR(20) NOT NULL DEFAULT 'real' COMMENT '模式：real真实调用，mock模拟返回',
  api_base_url VARCHAR(255) NOT NULL COMMENT 'OpenAI兼容接口基础地址',
  api_key VARCHAR(255) DEFAULT NULL COMMENT 'API Key，课程项目中直接保存，生产环境建议加密',
  model_name VARCHAR(100) NOT NULL COMMENT '模型名称',
  temperature DECIMAL(4,2) NOT NULL DEFAULT 0.30 COMMENT '生成温度',
  mock_on_failure TINYINT NOT NULL DEFAULT 1 COMMENT '真实调用失败时是否降级mock：1是，0否',
  enabled TINYINT NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI API配置表';

CREATE TABLE ai_chat_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '聊天记录ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  question TEXT NOT NULL COMMENT '用户问题',
  answer TEXT NOT NULL COMMENT 'AI回答',
  model_name VARCHAR(80) DEFAULT NULL COMMENT '模型名称',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI问答记录表';

CREATE TABLE ai_usage_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'AI使用日志ID',
  user_id BIGINT NOT NULL COMMENT '用户ID',
  note_id BIGINT DEFAULT NULL COMMENT '笔记ID',
  ai_type VARCHAR(40) NOT NULL COMMENT 'AI类型：SUMMARY/TAGS/CHAT/ADVICE',
  input_tokens INT NOT NULL DEFAULT 0 COMMENT '输入token估算',
  output_tokens INT NOT NULL DEFAULT 0 COMMENT '输出token估算',
  status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS' COMMENT '调用状态',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  KEY idx_ai_user (user_id),
  CONSTRAINT fk_ai_user FOREIGN KEY (user_id) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI调用日志表';

CREATE TABLE operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '操作日志ID',
  user_id BIGINT DEFAULT NULL COMMENT '操作用户ID',
  operation VARCHAR(100) NOT NULL COMMENT '操作名称',
  method VARCHAR(120) DEFAULT NULL COMMENT '请求方法',
  request_uri VARCHAR(255) DEFAULT NULL COMMENT '请求路径',
  ip VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  status VARCHAR(20) DEFAULT 'SUCCESS' COMMENT '状态',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统操作日志表';

CREATE TABLE login_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '登录日志ID',
  user_id BIGINT DEFAULT NULL COMMENT '用户ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  ip VARCHAR(64) DEFAULT NULL COMMENT 'IP地址',
  user_agent VARCHAR(255) DEFAULT NULL COMMENT '浏览器信息',
  status VARCHAR(20) NOT NULL COMMENT '登录状态',
  message VARCHAR(255) DEFAULT NULL COMMENT '提示信息',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='登录日志表';

SET FOREIGN_KEY_CHECKS = 1;
